### <a href="https://data8.org/sp26/reference/"> Python Reference Link <a>

Run the cell below so that we can set our modules up

In [1]:
import numpy as np
from datascience import *
import math

In [2]:
link = "https://raw.githubusercontent.com/humdskyline/data/main/first_class_survey_f2026.csv"
first_survey = Table.read_table(link)
first_survey.show(5)

### 1.  Try finding the commute time of the person in the fifth row

#### Start with the row restriction first

*Before writing any code, write comments that outline the steps you need to take. Then write the Python code that carries out each step.*

In [4]:
# get the commute_min column which returns an array
comm_times = first_survey.column("commute_min")
print(comm_times)

# get the item at index r
circled_time = comm_times.item(4)
print(circled_time)

[ 10  30  15  15   8  15  60  25  15  20  30   8   6  15  15  15  15  15
  30  10  30  15  10  30  90 120  10  15]
8

### 2.  Try finding the commute time of the person in the fifth row

#### Start with the column restriction first

*Before writing any code, write comments that outline the steps you need to take. Then write the Python code that carries out each step.*

In [9]:
#get the 5th row first
fifth_row = first_survey.take(4)
print(fifth_row)

#get the commute_min column
fifth_comm_time_col = fifth_row.column("commute_min")
print(fifth_comm_time_col)

#get that first element
the_time = fifth_comm_time_col.item(0)
print(the_time)

career      | sem_completed | units_taking | work_hours | sleep_hours | commute_min | coding_exp | data_exp | ds_confidence | think_time | ds_field              | color
Engineering | 1             | 12.5         | 15         | 5           | 8           | 1          | 1        | 10            | Late Night | Healthcare & Medicine | Purple
[8]
8

### 3.  Now that we know that our code for starting with the column restriction works, let's try writing the code as a compound statement

*Before writing any code, write comments that outline the steps you need to take. Then write the Python code that carries out each step.*

In [10]:
# get the commute_min column which returns an array, circled_time = comm_times.item(4)
straight_to_the_answer = first_survey.column("commute_min").item(4)
straight_to_the_answer

8

### 4. Now try writing the code for the process that starts with the row restriction first as a compound statement

*Before writing any code, write comments that outline the steps you need to take. Then write the Python code that carries out each step.*

In [12]:
#get the 5th row first, get the commute_min column, get that first element
straight_to_the_answer2 = first_survey.take(4).column("commute_min").item(0)
straight_to_the_answer2

8

### Let's remind ourselves how the table looks.  Write the code to display the first 10 rows of the dataset

In [13]:
first_survey.show(10)

### Let's shift gears and dive deeper into commute times.

Run the following cell to get the commute times

In [14]:
commute_times = first_survey.column("commute_min")
commute_times

array([ 10,  30,  15,  15,   8,  15,  60,  25,  15,  20,  30,   8,   6,
        15,  15,  15,  15,  15,  30,  10,  30,  15,  10,  30,  90, 120,
        10,  15])

### 5. Let's find the proportion of commute times longer than 45 minutes
#### a) Write comments that outline the steps needed to find the proportion of commute times longer than 45 minutes.
#### b) Under each comment, write the Python code that carries out that step.  
##### *Run your code one step at a time, checking each result before moving on.  You will probably want to create a new variable for each step*

In [16]:
# get the people with long commutes
long_commuters = first_survey.where("commute_min", are.above(45))
print(long_commuters)

#find the number of people with long commutes
num_long_commuters = long_commuters.num_rows
print(num_long_commuters)

#find the number of people in the survey
everyone = first_survey.num_rows


long_comm_prop = num_long_commuters / everyone
long_comm_prop

career              | sem_completed | units_taking | work_hours | sleep_hours | commute_min | coding_exp | data_exp | ds_confidence | think_time | ds_field             | color
Business/Finance    | 2             | 12           | 20         | 7           | 60          | 5          | 6        | 6             | Late Night | Finance & Economics  | Black
Not Sure Yet        | 6             | 12           | 20         | 7           | 90          | 1          | 1        | 5             | Evening    | Business & Marketing | Atelier Sparkling Blue
Computer Science/AI | 2             | 15           | 0          | 8           | 120         | 2          | 3        | 5             | Morning    | Science & Research   | Turquoise
3

0.10714285714285714

### 6. Let's find the 3rd longest commute time
#### a) Write comments that outline the steps needed to find the 3rd longest commute time.
#### b) Under each comment, write the Python code that carries out that step.  
##### *Run your code one step at a time, checking each result before moving on.  You will probably want to create a new variable for each step*

In [18]:
# sort the table by the commute time column so the longest times are at the top (descending)
sorted_by_col_desc = first_survey.sort("commute_min", descending=True)

#get the sorted column
sorted_col_desc = sorted_by_col_desc.column("commute_min")

# get the third one at index 2
third_long_comm = sorted_col_desc.item(2)
third_long_comm

60

### 7. Let's find the 5th shortest commute time
#### a) Write comments that outline the steps needed to find the 5th shortest commute time.
#### b) Under each comment, write the Python code that carries out that step.  
##### *Run your code one step at a time, checking each result before moving on.  You will probably want to create a new variable for each step*

In [20]:
# sort the table by the commute time column so the shortest times are at the top (ascending)
sorted_by_col_asc = first_survey.sort("commute_min", descending=False)

#get the sorted column
sorted_col_asc = sorted_by_col_asc.column("commute_min")

# get the fifth one at index 4
fifth_short_comm = sorted_col_asc.item(4)
fifth_short_comm

10